/**
 * The coordinator's email template library (from mca_heart_email_templates.html).
 * Placeholders: {{recipient}} {{sender}} {{paper}} {{journal}} {{deadline}}
 * {{manuscriptId}} {{link}} {{notes}}. The compose page (projects/[id]/email)
 * fills them from the paper and lets the admin edit before sending.
 */
export interface EmailTemplate {
  category: string;
  title: string;
  description: string;
  subject: string;
  body: string;
}

const RAW: EmailTemplate[] = [
  {category:"A. Progress and follow-ups", title:"Request manuscript progress update", description:"Check in on the current status of a manuscript or assigned task.", subject:"Progress update requested — {{paper}}", body:`Dear {{recipient}},\n\nI hope you are doing well. I am writing to check in on the progress of {{paper}}. Could you please share a brief update on the current status and any outstanding items?\n\nIf possible, please also let us know the anticipated timeline for the next milestone.\n\nThank you for your time.\n\nBest regards,\n{{sender}}`},
  {category:"A. Progress and follow-ups", title:"Request expected completion date", description:"Clarify when a draft or assigned task is likely to be completed.", subject:"Expected completion timeline — {{paper}}", body:`Dear {{recipient}},\n\nI hope you are well. Could you please let me know when you expect to complete the current task for {{paper}}? An estimated date will help us coordinate the remaining steps and plan the project timeline.\n\nPlease let me know if anything is likely to affect that timeline.\n\nThank you.\n\nBest regards,\n{{sender}}`},
  {category:"A. Progress and follow-ups", title:"Reminder: drafting deadline approaching", description:"A courteous reminder before an agreed internal deadline.", subject:"Reminder: upcoming deadline for {{paper}}", body:`Dear {{recipient}},\n\nThis is a friendly reminder that the current deadline for {{paper}} is {{deadline}}. Please let us know whether the work is on track or if any support is needed to meet the timeline.\n\nThank you for your help in keeping the project moving.\n\nBest regards,\n{{sender}}`},
  {category:"A. Progress and follow-ups", title:"Follow up on overdue task", description:"Follow up when a task has passed its agreed deadline.", subject:"Follow-up on pending task — {{paper}}", body:`Dear {{recipient}},\n\nI am following up on the pending task for {{paper}}, which was expected by {{deadline}}. Could you please share the current status and an updated expected completion date?\n\nIf there is a blocker or the timeline needs to be adjusted, please let us know so we can plan accordingly.\n\nThank you.\n\nBest regards,\n{{sender}}`},
  {category:"A. Progress and follow-ups", title:"Follow up on an unanswered email", description:"Polite follow-up when an earlier message has not received a response.", subject:"Follow-up: {{paper}}", body:`Dear {{recipient}},\n\nI hope you are doing well. I wanted to follow up on my previous email regarding {{paper}} in case it was missed. When convenient, could you please share your update or let me know if you need any additional information from me?\n\nThank you for your time.\n\nBest regards,\n{{sender}}`},
  {category:"A. Progress and follow-ups", title:"Check in on an inactive/stalled manuscript", description:"Re-establish next steps for a project with no recent activity.", subject:"Next steps for {{paper}}", body:`Dear {{recipient}},\n\nI am checking in regarding {{paper}}, as there has not been a recent update in the project pipeline. Could you please advise on its current status and whether we should continue with the existing plan or revise the next steps?\n\nIt would be helpful to agree on a realistic timeline and identify any outstanding requirements.\n\nBest regards,\n{{sender}}`},
  {category:"A. Progress and follow-ups", title:"Request weekly project update", description:"Collect concise, recurring updates from collaborators.", subject:"Weekly update — {{paper}}", body:`Dear {{recipient}},\n\nCould you please send a brief update on {{paper}} for this week? Please include work completed, items currently in progress, any blockers, and the next planned steps with estimated dates.\n\nA concise update is sufficient and will help us keep the project tracker current.\n\nThank you.\n\nBest regards,\n{{sender}}`},

  {category:"B. Drafting and scientific review", title:"Request initial manuscript draft", description:"Ask the assigned drafter to share the first complete draft.", subject:"Initial draft requested — {{paper}}", body:`Dear {{recipient}},\n\nI hope you are well. I am checking on the initial draft of {{paper}}. Could you please share the current working document by {{deadline}}, or let us know when a complete draft is likely to be ready?\n\nPlease include the relevant sections, tables, figures, and references available at this stage.\n\nWorking document: {{link}}\n\nBest regards,\n{{sender}}`},
  {category:"B. Drafting and scientific review", title:"Request manuscript review and feedback", description:"Invite a co-author or supervisor to review a draft.", subject:"Review requested — {{paper}}", body:`Dear {{recipient}},\n\nI hope you are doing well. Could you please review the current draft of {{paper}} and share any scientific, methodological, or editorial feedback by {{deadline}}? Please feel free to use tracked changes or comments in the working document.\n\nDocument: {{link}}\n\nThank you for your time and input.\n\nBest regards,\n{{sender}}`},
  {category:"B. Drafting and scientific review", title:"Request revisions based on feedback", description:"Ask the drafter to address feedback already received.", subject:"Revisions requested — {{paper}}", body:`Dear {{recipient}},\n\nThank you for preparing the draft of {{paper}}. Please address the comments and suggested changes in the document and return the revised version by {{deadline}}. Where a suggestion is not adopted, please add a brief explanation so the decision can be reviewed.\n\nWorking document: {{link}}\n\nThank you.\n\nBest regards,\n{{sender}}`},
  {category:"B. Drafting and scientific review", title:"Follow up on pending co-author comments", description:"Request comments from co-authors who have not yet responded.", subject:"Reminder: co-author comments for {{paper}}", body:`Dear {{recipient}},\n\nI am following up on the request for your comments on {{paper}}. When possible, could you please share any feedback by {{deadline}}? If you have no further changes, a brief confirmation would also help us coordinate the next step.\n\nDocument: {{link}}\n\nThank you for your contribution.\n\nBest regards,\n{{sender}}`},
  {category:"B. Drafting and scientific review", title:"Request clarification of methods or results", description:"Resolve a specific analysis, methods, or results question.", subject:"Clarification needed for {{paper}}", body:`Dear {{recipient}},\n\nWhile reviewing {{paper}}, I noted that clarification is needed regarding the methods/results, particularly the item below. Could you please confirm the intended interpretation and, where relevant, point us to the supporting analysis or source?\n\n{{notes}}\n\nThis will help ensure that the manuscript accurately reflects the analysis.\n\nThank you.\n\nBest regards,\n{{sender}}`},
  {category:"B. Drafting and scientific review", title:"Request missing data, tables, or figures", description:"Request missing materials needed to complete the paper.", subject:"Outstanding materials needed — {{paper}}", body:`Dear {{recipient}},\n\nTo complete {{paper}}, could you please share the outstanding data, table(s), figure(s), or supplementary materials listed below by {{deadline}}? Please also flag anything that is unavailable or requires further analysis.\n\n{{notes}}\n\nWorking document: {{link}}\n\nThank you.\n\nBest regards,\n{{sender}}`},
  {category:"B. Drafting and scientific review", title:"Request final manuscript approval", description:"Ask authors to confirm that the final manuscript version is accurate.", subject:"Final manuscript review — {{paper}}", body:`Dear {{recipient}},\n\nPlease review the current final version of {{paper}} and confirm that your name, affiliation, contribution, and any comments on the scientific content are accurate. Please send any essential corrections by {{deadline}}.\n\nDocument: {{link}}\n\nThis check is intended to ensure that the submitted version reflects the authors' agreed content.\n\nBest regards,\n{{sender}}`},
  {category:"B. Drafting and scientific review", title:"Share revised manuscript for review", description:"Circulate an updated draft after incorporating changes.", subject:"Revised draft for review — {{paper}}", body:`Dear {{recipient}},\n\nPlease find the updated draft of {{paper}} for your review. The changes reflect the feedback received so far. Could you please check the revised sections and share any remaining comments by {{deadline}}?\n\nDocument: {{link}}\n\nThank you for your continued input.\n\nBest regards,\n{{sender}}`},

  {category:"C. Submission preparation", title:"Request author details and affiliations", description:"Collect or verify author names, degrees, and institutional affiliations.", subject:"Author details and affiliations — {{paper}}", body:`Dear {{recipient}},\n\nAs we prepare {{paper}} for submission to {{journal}}, could you please confirm your full name as it should appear in the publication, your current institutional affiliation(s), and any preferred degree or professional designation required by the journal?\n\nPlease check spelling and affiliation details carefully.\n\nThank you.\n\nBest regards,\n{{sender}}`},
  {category:"C. Submission preparation", title:"Confirm author list and author order", description:"Verify the author list and agreed order before submission.", subject:"Please confirm author list and order — {{paper}}", body:`Dear {{recipient}},\n\nBefore submitting {{paper}} to {{journal}}, we are confirming the proposed author list and order. Please review the list in the working document and let us know promptly if anything needs correction or discussion.\n\nDocument: {{link}}\n\nPlease note that the final author list and order should reflect the authors' agreed contributions and applicable authorship criteria.\n\nBest regards,\n{{sender}}`},
  {category:"C. Submission preparation", title:"Notify team of planned submission", description:"Tell the team which journal and date are planned for submission.", subject:"Planned submission — {{paper}} to {{journal}}", body:`Dear team,\n\nWe are planning to submit {{paper}} to {{journal}} on or around {{deadline}}. Please review any outstanding tasks assigned to you and let us know immediately if a material issue may affect submission readiness.\n\nWorking document: {{link}}\n\nThank you to everyone who has contributed.\n\nBest regards,\n{{sender}}`},
  {category:"C. Submission preparation", title:"Notify team: manuscript submitted", description:"Confirm that a manuscript has been submitted.", subject:"Manuscript submitted — {{paper}}", body:`Dear team,\n\nThis is to confirm that {{paper}} has been submitted to {{journal}}. We will share any editorial updates or requests for additional information as they become available.\n\nSubmission reference: {{manuscriptId}}\n\nThank you to everyone who contributed to preparing the manuscript.\n\nBest regards,\n{{sender}}`},
  {category:"C. Submission preparation", title:"Share journal submission confirmation and manuscript ID", description:"Circulate the submission receipt and reference number.", subject:"Submission confirmation and manuscript ID — {{paper}}", body:`Dear team,\n\nThe journal submission for {{paper}} has been completed. The submission reference is {{manuscriptId}}. Please retain this information for future correspondence with {{journal}}.\n\nSubmission / manuscript link: {{link}}\n\nI will update the team when there is a substantive change in status.\n\nBest regards,\n{{sender}}`},

  {category:"D. Journal status and editorial decisions", title:"Request journal status update", description:"Ask the journal for a courteous status update after a reasonable wait.", subject:"Status inquiry — {{paper}} ({{manuscriptId}})", body:`Dear Editorial Office,\n\nI hope you are well. I am writing to inquire about the current status of our manuscript, “{{paper}}” (manuscript ID: {{manuscriptId}}), submitted to {{journal}} on {{deadline}}.\n\nWe understand that peer review takes time and appreciate the work involved. If an update is available, we would be grateful to hear whether the manuscript is still under editorial consideration.\n\nThank you for your assistance.\n\nKind regards,\n{{sender}}`},
  {category:"D. Journal status and editorial decisions", title:"Notify team: manuscript with editor", description:"Report that the manuscript has reached the editor stage.", subject:"Editorial status update — {{paper}}", body:`Dear team,\n\nThe current status of {{paper}} at {{journal}} indicates that it is with the editor. This means the manuscript is at an editorial assessment stage; it does not yet indicate an outcome.\n\nManuscript ID: {{manuscriptId}}\n\nI will share further updates when the journal posts a new decision or status.\n\nBest regards,\n{{sender}}`},
  {category:"D. Journal status and editorial decisions", title:"Notify team: manuscript under review", description:"Inform collaborators that peer review is underway.", subject:"Manuscript under review — {{paper}}", body:`Dear team,\n\nThe journal status for {{paper}} at {{journal}} now indicates that the manuscript is under review. There is no decision to report at this stage. We will continue to monitor the submission and share any editorial communication when received.\n\nManuscript ID: {{manuscriptId}}\n\nBest regards,\n{{sender}}`},
  {category:"D. Journal status and editorial decisions", title:"Follow up with journal editorial office", description:"Send a follow-up about a specific journal query or administrative issue.", subject:"Follow-up regarding {{paper}} ({{manuscriptId}})", body:`Dear Editorial Office,\n\nI am following up on our previous correspondence regarding “{{paper}}” (manuscript ID: {{manuscriptId}}). Could you please advise whether any further information or action is required from the authors?\n\n{{notes}}\n\nThank you for your assistance.\n\nKind regards,\n{{sender}}`},
  {category:"D. Journal status and editorial decisions", title:"Notify team: revision requested", description:"Tell collaborators that the editor has invited or required a revision.", subject:"Revision requested — {{paper}}", body:`Dear team,\n\nWe have received a revision decision for {{paper}} from {{journal}}. The reviewer and editor comments should now be reviewed and assigned so that we can prepare a coordinated response.\n\nManuscript ID: {{manuscriptId}}\nRevision deadline: {{deadline}}\nDecision letter / manuscript link: {{link}}\n\nI will circulate proposed responsibilities and timelines shortly.\n\nBest regards,\n{{sender}}`},
  {category:"D. Journal status and editorial decisions", title:"Notify team: manuscript accepted", description:"Announce formal acceptance without implying publication has already occurred.", subject:"Manuscript accepted — {{paper}}", body:`Dear team,\n\nI am pleased to share that {{paper}} has been accepted by {{journal}}. Thank you all for your work and contributions throughout the project and submission process.\n\nManuscript ID: {{manuscriptId}}\n\nWe will follow up on any production, proofing, or publication steps as the journal provides them.\n\nBest regards,\n{{sender}}`},
  {category:"D. Journal status and editorial decisions", title:"Notify team: manuscript rejected", description:"Communicate rejection neutrally and focus on next steps.", subject:"Editorial decision received — {{paper}}", body:`Dear team,\n\nWe have received a decision from {{journal}} regarding {{paper}}. Unfortunately, the manuscript was not accepted for publication at this journal.\n\nI suggest that we review the editor and reviewer comments, identify any changes that would strengthen the manuscript, and then discuss an appropriate next journal.\n\nDecision letter: {{link}}\n\nThank you for your work on the project.\n\nBest regards,\n{{sender}}`},
  {category:"D. Journal status and editorial decisions", title:"Discuss next journal after rejection", description:"Coordinate a data-informed next-journal decision after rejection.", subject:"Next-journal options for {{paper}}", body:`Dear team,\n\nFollowing the decision from {{journal}}, we should agree on the next destination for {{paper}}. Please consider journal scope, audience, recent comparable publications, review timelines where known, and submission requirements.\n\nIf you have a suitable journal suggestion, please share the rationale and any required manuscript changes by {{deadline}}.\n\nCurrent manuscript / decision letter: {{link}}\n\nBest regards,\n{{sender}}`},
  {category:"D. Journal status and editorial decisions", title:"Discuss target journal selection", description:"Compare possible target journals before submission.", subject:"Target journal discussion — {{paper}}", body:`Dear team,\n\nWe need to finalize a target journal for {{paper}}. Please suggest journals that fit the manuscript's topic, design, and audience, and consider relevant scope, recent publications, indexing, article type, fees, and realistic acceptance expectations.\n\nPlease share your recommendation and rationale by {{deadline}}.\n\nDraft: {{link}}\n\nBest regards,\n{{sender}}`},

  {category:"E. Revisions and resubmissions", title:"Request co-author input on reviewer comments", description:"Ask authors to review the decision letter and contribute responses.", subject:"Co-author input requested: reviewer comments — {{paper}}", body:`Dear {{recipient}},\n\nWe have received reviewer comments for {{paper}} and are preparing the revision. Could you please review the comments relevant to your area and suggest responses or manuscript changes by {{deadline}}?\n\nDecision letter and response document: {{link}}\n\nPlease flag any comment that requires additional analysis or a team discussion.\n\nThank you.\n\nBest regards,\n{{sender}}`},
  {category:"E. Revisions and resubmissions", title:"Assign reviewer comments for response", description:"Assign specific reviewer points to collaborators.", subject:"Reviewer comment assignments — {{paper}}", body:`Dear team,\n\nTo coordinate the revision of {{paper}}, please review the assigned reviewer comments in the response document. Each response should address the point directly and identify any corresponding change in the manuscript. If a request cannot be fulfilled, please propose a clear, evidence-based explanation.\n\nResponse document: {{link}}\nDeadline for assigned responses: {{deadline}}\n\nPlease let me know early if an assignment needs to be redistributed.\n\nBest regards,\n{{sender}}`},
  {category:"E. Revisions and resubmissions", title:"Request revised manuscript by deadline", description:"Set a clear due date for completing the revision.", subject:"Revised manuscript due {{deadline}} — {{paper}}", body:`Dear {{recipient}},\n\nCould you please complete your assigned changes for {{paper}} by {{deadline}} so we have time to integrate the responses, check consistency, and prepare the resubmission?\n\nWorking document: {{link}}\n\nPlease let me know promptly if the requested timeline is not feasible.\n\nBest regards,\n{{sender}}`},
  {category:"E. Revisions and resubmissions", title:"Reminder: revision deadline approaching", description:"Remind collaborators of the journal's revision deadline.", subject:"Reminder: journal revision deadline — {{paper}}", body:`Dear team,\n\nA reminder that the current revision deadline for {{paper}} at {{journal}} is {{deadline}}. Please complete outstanding assigned items as soon as possible so the response letter and revised manuscript can be checked before resubmission.\n\nManuscript ID: {{manuscriptId}}\nWorking document: {{link}}\n\nPlease notify me of any potential delay or unresolved reviewer point.\n\nBest regards,\n{{sender}}`},
  {category:"E. Revisions and resubmissions", title:"Share response-to-reviewers draft", description:"Circulate the response letter for scientific and editorial review.", subject:"Response-to-reviewers draft for review — {{paper}}", body:`Dear {{recipient}},\n\nPlease review the current response-to-reviewers document for {{paper}}. We would appreciate feedback on whether each point is answered clearly, whether the responses are supported by the revised manuscript or analysis, and whether any requested change remains unresolved.\n\nDocument: {{link}}\nPlease send feedback by {{deadline}}.\n\nThank you.\n\nBest regards,\n{{sender}}`},
  {category:"E. Revisions and resubmissions", title:"Request approval of revised manuscript", description:"Ask the team to check the final revision package before resubmission.", subject:"Final revision package review — {{paper}}", body:`Dear {{recipient}},\n\nThe revised manuscript and response letter for {{paper}} are ready for a final check. Please review the files for scientific accuracy, consistency between the responses and manuscript, and any remaining errors by {{deadline}}.\n\nFiles: {{link}}\n\nPlease send any essential corrections or confirm that you have no further comments.\n\nBest regards,\n{{sender}}`},
  {category:"E. Revisions and resubmissions", title:"Notify team: revised manuscript resubmitted", description:"Confirm that the revision has been resubmitted to the journal.", subject:"Revised manuscript resubmitted — {{paper}}", body:`Dear team,\n\nThe revised version of {{paper}} has been resubmitted to {{journal}}. Thank you for helping address the reviewers' and editor's comments.\n\nManuscript ID: {{manuscriptId}}\nSubmission details: {{link}}\n\nWe will share further updates when the journal communicates a new decision.\n\nBest regards,\n{{sender}}`},

  {category:"F. Acceptance and publication", title:"Request final proof review", description:"Ask authors to check typeset proofs for errors and accuracy.", subject:"Proof review requested — {{paper}}", body:`Dear {{recipient}},\n\nThe journal has provided the page proofs for {{paper}}. Please review the proofs carefully for typesetting errors, author names and affiliations, tables, figures, references, and any discrepancies from the accepted manuscript. Please avoid introducing unnecessary substantive changes at this stage.\n\nProofs: {{link}}\nDeadline: {{deadline}}\n\nPlease return any corrections by the stated deadline.\n\nBest regards,\n{{sender}}`},
  {category:"F. Acceptance and publication", title:"Reminder: proof corrections due", description:"Remind authors of an approaching proof-correction deadline.", subject:"Reminder: proof corrections due {{deadline}} — {{paper}}", body:`Dear {{recipient}},\n\nThis is a reminder that corrections to the proofs for {{paper}} are due by {{deadline}}. Please send any remaining corrections before the deadline so we can return a complete set to the journal.\n\nProofs: {{link}}\n\nThank you for your prompt attention.\n\nBest regards,\n{{sender}}`},
  {category:"F. Acceptance and publication", title:"Notify team: paper published", description:"Announce publication once the article is available online or in issue.", subject:"Now published — {{paper}}", body:`Dear team,\n\nI am pleased to share that {{paper}} has been published in {{journal}}. Thank you to everyone involved in the study, analysis, drafting, review, and submission process.\n\nArticle link / DOI: {{link}}\n\nPlease feel free to share the published article through appropriate professional channels.\n\nBest regards,\n{{sender}}`},
  {category:"F. Acceptance and publication", title:"Share published paper and DOI", description:"Send collaborators the final publication link and DOI.", subject:"Published article and DOI — {{paper}}", body:`Dear team,\n\nThe published version of {{paper}} is now available. The article link / DOI is: {{link}}\n\nJournal: {{journal}}\n\nThank you again for your contributions. Please use the publisher's version when sharing or citing the paper.\n\nBest regards,\n{{sender}}`},

  {category:"G. Abstracts and conferences", title:"Request abstract progress update", description:"Check the status of an abstract being prepared for a meeting.", subject:"Abstract progress update — {{paper}}", body:`Dear {{recipient}},\n\nCould you please share a brief update on the abstract for {{paper}}? It would be helpful to know which sections are complete, what remains outstanding, and whether the planned submission date of {{deadline}} is still achievable.\n\nWorking document: {{link}}\n\nThank you.\n\nBest regards,\n{{sender}}`},
  {category:"G. Abstracts and conferences", title:"Request abstract review and feedback", description:"Invite review of an abstract before submission.", subject:"Abstract review requested — {{paper}}", body:`Dear {{recipient}},\n\nCould you please review the current abstract for {{paper}} and send any scientific or editorial feedback by {{deadline}}? Please pay particular attention to the accuracy of the results, consistency of the conclusion with the findings, word limit, and conference-specific requirements.\n\nDraft: {{link}}\n\nThank you for your input.\n\nBest regards,\n{{sender}}`},
  {category:"G. Abstracts and conferences", title:"Request final abstract approval", description:"Confirm agreement on an abstract's final text before submission.", subject:"Final abstract check — {{paper}}", body:`Dear {{recipient}},\n\nPlease review the final abstract for {{paper}} and let us know by {{deadline}} if you identify any essential factual or authorship-related corrections. We are aiming to ensure that the submitted version is accurate and consistent with the underlying analysis.\n\nFinal draft: {{link}}\n\nThank you.\n\nBest regards,\n{{sender}}`},
  {category:"G. Abstracts and conferences", title:"Reminder: conference submission deadline", description:"Remind the team about an upcoming abstract or conference deadline.", subject:"Reminder: conference deadline {{deadline}} — {{paper}}", body:`Dear team,\n\nA reminder that the deadline for the {{journal}} submission related to {{paper}} is {{deadline}}. Please complete your outstanding assigned tasks and flag any concerns as early as possible so there is time for final quality checks and submission.\n\nWorking document: {{link}}\n\nBest regards,\n{{sender}}`},
  {category:"G. Abstracts and conferences", title:"Notify team: abstract submitted", description:"Confirm completion of conference abstract submission.", subject:"Abstract submitted — {{paper}}", body:`Dear team,\n\nThis is to confirm that the abstract for {{paper}} has been submitted to {{journal}}. We will share any confirmation, presentation details, or decision notice when available.\n\nSubmission reference: {{manuscriptId}}\n\nThank you to everyone who contributed.\n\nBest regards,\n{{sender}}`},
  {category:"G. Abstracts and conferences", title:"Notify team: abstract accepted or rejected", description:"Communicate a conference decision and the next required actions.", subject:"Conference decision — {{paper}}", body:`Dear team,\n\nWe have received the conference decision for {{paper}} from {{journal}}: [accepted / not accepted].\n\nIf accepted, we will coordinate any presentation, poster, registration, and disclosure requirements. If not accepted, we can review any feedback and decide whether another venue is appropriate.\n\nDecision notice: {{link}}\n\nBest regards,\n{{sender}}`},
  {category:"G. Abstracts and conferences", title:"Request presentation or poster materials", description:"Ask the presenter to prepare slides or a poster by a specific date.", subject:"Presentation/poster materials — {{paper}}", body:`Dear {{recipient}},\n\nCould you please prepare the presentation or poster materials for {{paper}} and share a draft by {{deadline}}? Please follow the conference's formatting, size, disclosure, and branding requirements. We should also verify that all data and conclusions match the accepted abstract and final analysis.\n\nRequirements / working file: {{link}}\n\nThank you.\n\nBest regards,\n{{sender}}`},

  {category:"H. Other", title:"Schedule manuscript meeting", description:"Arrange a short meeting to align on manuscript status and next steps.", subject:"Meeting request: {{paper}}", body:`Dear {{recipient}},\n\nCould we arrange a brief meeting to review the status of {{paper}}, resolve outstanding questions, and agree on responsibilities and timelines? Please let me know your availability around {{deadline}} or suggest another suitable time.\n\nProposed topics: current status, outstanding tasks, decisions needed, and next milestones.\n\nBest regards,\n{{sender}}`},
  {category:"H. Other", title:"Request a meeting to resolve project delays", description:"Bring relevant collaborators together to address blockers and reset the plan.", subject:"Meeting to address project timeline — {{paper}}", body:`Dear {{recipient}},\n\nI suggest a short meeting to discuss the delays affecting {{paper}}, clarify the remaining blockers, and agree on a realistic revised timeline. The aim is to identify practical next steps and confirm ownership for each outstanding item.\n\nPlease share your availability for {{deadline}} or propose a suitable alternative.\n\nBest regards,\n{{sender}}`},
  {category:"H. Other", title:"Request missing project information", description:"Ask for project-related information not covered by another template.", subject:"Information needed for {{paper}}", body:`Dear {{recipient}},\n\nI am following up to request the information below for {{paper}}. Could you please share it by {{deadline}}, or let me know if it is unavailable?\n\n{{notes}}\n\nThis will help us keep the project record accurate and move the next steps forward.\n\nThank you.\n\nBest regards,\n{{sender}}`},
  {category:"H. Other", title:"Custom email / other", description:"A flexible starting point for an email not covered by a standard template.", subject:"Regarding {{paper}}", body:`Dear {{recipient}},\n\nI hope you are doing well. I am writing regarding {{paper}}.\n\n{{notes}}\n\nPlease let me know if you have any questions or need further information.\n\nBest regards,\n{{sender}}`},
];

// No em dashes in anything we send: "Subject — {{paper}}" becomes "Subject: {{paper}}".
const noDash = (s: string) => s.replace(/\s*—\s*/g, ': ').replace(/:\s*:/g, ':');

export const EMAIL_TEMPLATES: EmailTemplate[] = RAW.map((t) => ({
  ...t,
  subject: noDash(t.subject),
  body: noDash(t.body),
}));
